---
deployment:
  tasks:
    - source ~/.nvm/nvm.sh
    - nvm install 18
    - nvm use 18
    - export DEPLOYPATH=/home/naviyan2/public_html/instatrack
    - mkdir -p $DEPLOYPATH
    - /bin/cp -r .next $DEPLOYPATH/
    - /bin/cp -r public $DEPLOYPATH/
    - /bin/cp -r package.json $DEPLOYPATH/
    - /bin/cp -r package-lock.json $DEPLOYPATH/
    - /bin/cp -r server.js $DEPLOYPATH/
    - cd $DEPLOYPATH
    - npm install --production
    - NODE_ENV=production npm run build
    - pm2 restart all || pm2 start server.js --name "instatrack"
